name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: LightWhite520
          template: classic
          base: header, activity, repositories, metadata

          config_timezone: Asia/Shanghai
          config_display: large
          config_animations: yes
          config_octicon: yes
          config_theme: dark

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_sort: lines
          plugin_languages_categories: programming

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_lines: yes
          plugin_lines_sections: base, repositories

          plugin_repositories: yes
          plugin_repositories_sort: updated
          plugin_activity: yes
          plugin_stars: no

          plugin_topics: yes
          plugin_topics_limit: 12
