name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: LightWhite520
          template: classic
          base: header, activity, repositories, metadata

          config_timezone: Asia/Shanghai
          config_display: large
          config_animations: yes
          config_octicon: yes

          # 语言统计（含私有）
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes

          # 提交日历
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # 代码行统计（含私有）
          plugin_lines: yes
          plugin_lines_sections: base, repositories

          # 贡献趋势
          plugin_activity: yes

          # 关闭 stars
          plugin_stars: no

          # 技术主题
          plugin_topics: yes
          plugin_topics_limit: 12

          # 终端风
          config_theme: dark
