name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: LightWhite520
          template: terminal
          base: header, activity, metadata

          config_timezone: Asia/Beijing
          config_display: large
          config_animations: no

          plugin_languages: yes
          plugin_languages_indepth: yes

          plugin_lines: yes
          plugin_lines_sections: base

          plugin_isocalendar: yes

          plugin_stars: no
