name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: LightWhite520
          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Singapore

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_lines: yes
          plugin_lines_sections: base

          plugin_followup: yes
          plugin_followup_sections: user

          plugin_stars: yes

          plugin_topics: yes
          plugin_topics_limit: 10

          config_display: large
          config_octicon: yes
          config_animations: yes
